//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruchy
    {
        public int Id { get; set; }
        public int Id_partii { get; set; }
        public int nr_ruchu { get; set; }
        public string skad { get; set; }
        public string dokad { get; set; }
    
        public virtual Partia Partia { get; set; }
    }
}
